development:
  adapter: postgresql
  encoding: unicode
  database: tunecore
  pool: 5
  username: eyk23
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: tunecore
  pool: 5
  username: eyk23
  password: